### ISSUE TITLE
Use gelf error.

### ISSUE THREAD

**Issue by steinliber** [emsearcy/fluent-plugin-gelf#32]
I install this plugin in /etc/td-agent/out_gelf.rb, but when i run service td-agent restart, Then, this is error

```
Restarting td-agent: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- gelf (LoadError)
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /etc/td-agent/plugin/out_gelf.rb:15:in `initialize'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin.rb:128:in `new'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin.rb:128:in `new_impl'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin.rb:59:in `new_output'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/out_copy.rb:46:in `block in configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/out_copy.rb:39:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin/out_copy.rb:39:in `configure'
```

look like it require gelf, can someone help me

**Comment by rusia-rak** [comment]
@steinliber 

/usr/sbin/td-agent-gem install gelf

Source: http://www.fluentd.org/guides/recipes/graylog2

**Comment by steinliber** [comment]
Thanks
